name: Build and Push kube-api-network-access-check

on:
  push:
    branches:
      - main
    paths:
      - 'kube-api-network-access-check/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push (multi-arch)
        uses: docker/build-push-action@v5
        with:
          context: ./kube-api-network-access-check
          file: ./kube-api-network-access-check/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/kube-api-network-access-check:latest
            ghcr.io/${{ github.repository_owner }}/kube-api-network-access-check:${{ github.sha }}
